spring:
  application:
    name: interview-beater-service
  lifecycle:
    timeout-per-shutdown-phase: 30s   # сколько ждать незавершенные запросы (максимум)

server:
  port: 8080
  shutdown: graceful

#  datasource:
#    url: jdbc:postgresql://localhost:5433/interviewBeaterService
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true

#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true

#logging:
#  level:
#    com.github.interviewbeaterservice: DEBUG
#    org.hibernate.SQL: DEBUG